fixed init script for jabberd-2.2.16, as i couldn't get 2.2.17 to compile

diff --git a/net-im/jabberd2/files/jabberd2-2.2.16.init b/net-im/jabberd2/files/jabberd2-2.2.16.init
--- a/net-im/jabberd2/files/jabberd2-2.2.16.init
+++ b/net-im/jabberd2/files/jabberd2-2.2.16.init
@@ -32,6 +32,11 @@ start() {
 	local services
 	services=$(grep -v ^# /etc/jabber/jabberd.cfg | grep '..*' | awk '{print $1 ":" $2}')
 	eindent
+
+	if [ ! -d /var/run/jabber ] ; then
+		mkdir /var/run/jabber || die "Can't create run directory /var/run/jabber"
+	fi
+
 	for service in ${services}; do
 
 		cfgfile=$(echo ${service} | cut -d ':' -f 2)
